import React from 'react';
import './Mobile.scss';

const Mobile = () => {
    return (
        <div className='MobileContent figma-navigation'>
            <div className="headTitleBg">
                <div className="container">
                    <h1><span>2.</span> Mobile</h1>
                </div>
            </div>
            <div className='page-content padtp0'>
                <div className='container'>

                   
                    <div className='navigation'>
                        
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-41926&viewport=29838%2C-4921%2C0.33&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A41926&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">TATA Memorial Hospital Homepage</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-40916&viewport=54493%2C-9255%2C0.61&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A40916&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">TATA Memorial Centre Homepage</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-42692&viewport=33434%2C-5577%2C0.39&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A42692&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Open left nav</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-38351&viewport=16311%2C-3039%2C0.2&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A38351&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Login</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=247-135730&viewport=570%2C-3397%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=247%3A135730&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about financial assistance</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-35687&viewport=5679%2C-1345%2C0.08&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A35687&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Book an appointment (new patient)</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=554-80286&viewport=34910%2C-12428%2C0.6&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=554%3A80286&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Book an appointment (already registered patient)</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-39124&viewport=2976%2C-1019%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A39124&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn discharge process</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-32024&viewport=2976%2C-1019%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A32024&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Find a cancer support group</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-33160&viewport=2082%2C-1027%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A33160&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about doctor visit process</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-56075&viewport=1554%2C-1087%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A56075&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Register for a conference</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-63988&viewport=-402%2C-2406%2C0.11&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A63988&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Donation</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-48222&viewport=-3141%2C-1419%2C0.08&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A48222&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Contact us</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-51087&viewport=-1167%2C-1361%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A51087&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Find course details</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-45485&viewport=-1541%2C-1325%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A45485&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Explore specialities</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-71470&viewport=5127%2C-4069%2C0.08&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A71470&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Explore technology</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-73583&viewport=4971%2C-4369%2C0.08&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A73583&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Explore treatments</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-65563&viewport=27668%2C-19084%2C0.34&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A65563&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Doctor's directory</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-49636&viewport=-2487%2C-1491%2C0.08&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A49636&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">RTI</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-58996&viewport=-3509%2C-1164%2C0.07&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A58996&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about the research faculty</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-60202&viewport=-41791%2C-13942%2C0.71&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A60202&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Search for patient & visitor guidelines</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-52561&viewport=-10067%2C-2888%2C0.16&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A52561&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Download research related resources</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-67856&viewport=15303%2C-8151%2C0.16&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A67856&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Read the director's message</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-67370&viewport=8990%2C-5489%2C0.1&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A67370&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Why choose TATA Memorial Hospital</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-69014&viewport=18309%2C-13573%2C0.24&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A69014&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Find a ongoing research</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-70220&viewport=11990%2C-9592%2C0.18&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A70220&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about preventative oncology</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-74728&viewport=7093%2C-6825%2C0.13&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A74728&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Upcoming projects</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-75138&viewport=6701%2C-6961%2C0.13&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A75138&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about nutrition guidance</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-76063&viewport=5981%2C-7141%2C0.13&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A76063&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about breast screening</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-77643&viewport=2802%2C-3021%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A77643&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about accommodation & stay</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-78597&viewport=2332%2C-2987%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A78597&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Ethics committee</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-79513&viewport=2266%2C-2987%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A79513&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Quarterly digest</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-80408&viewport=1934%2C-2977%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A80408&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Mission & vision</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-81354&viewport=1364%2C-3021%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A81354&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Learn about mental health support</a>
                        <a href="https://www.figma.com/proto/tbXQDC0elozr5VtOYY6wH1/TMC-Client-File?node-id=238-82307&viewport=1310%2C-3033%2C0.06&t=uqbVZxaP1FNnXyVh-0&scaling=scale-down&content-scaling=fixed&starting-point-node-id=238%3A82307&show-proto-sidebar=1" className="sub-menu" target="_blank" rel="noopener noreferrer">Read about life after cancer</a>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Mobile;